### ISSUE TITLE
勘误：项目地址变更

### ISSUE THREAD

**Issue by Weilet** [jobbole/awesome-cpp-cn#14]
<img width="759" alt="Snipaste_2019-11-23_20-54-36" src="https://user-images.githubusercontent.com/32561597/69479002-82467d00-0e33-11ea-9662-f5101dac1c2e.png">

*https://github.com/joyent/libuv* -> *https://github.com/libuv/libuv*

**Comment by tangyouhua** [comment]
感谢提醒，已更新
