### ISSUE TITLE
recommand

### ISSUE THREAD

**Issue by yanminhui** [jobbole/awesome-cpp-cn#6]
-  @nlohmann
[json](https://github.com/nlohmann/json)

- @yanminhui 
[tinylog](https://github.com/yanminhui/tinylog)

**Comment by tangyouhua** [comment]
Thanks for contribution:)
json @nlohmann has been added in cpp list, and marked you as contributor.
For tinylog, it is a cool project but doesn't meet the standard (500+ github stars).
I will keep watching this project. Cheers.
